[build]
command = "npm run build"
publish = ".next"

[build.environment]
NODE_OPTIONS = "--max_old_space_size=8192"

[template.environment]
OPENAI_API_KEY = "set your OpenAI API Key"
ACCESS_CODE = "set your password to protect your api key"
